### ISSUE TITLE
This app has not yet been verified by Google in order to use Google Sign in

### ISSUE THREAD

**Issue by LPchong** [nuket/google-sheets-geocoding-macro#12]
I tried to run the code and authorise the access but received below message. 
_Sign in with Google temporarily disabled for this app
This app has not yet been verified by Google in order to use Google Sign in._

Any ideas how to fix it?

**Comment by Krukarius** [comment]
Yep, I have got exactly the same problem!

**Comment by nuket** [comment]
Without having time to look at it, I'm gonna guess they tightened up their APIs to require some kind of an API key for the Geocoder constructor, which this code never used since it was before this code's time.

https://github.com/nuket/google-sheets-geocoding-macro/blob/master/Code.gs#L345
https://github.com/nuket/google-sheets-geocoding-macro/blob/master/Code.gs#L400

**Comment by nuket** [comment]
This probably does the trick:
https://developers.google.com/apps-script/reference/maps/maps#setAuthentication(String,String)

**Comment by Penworks** [comment]
I had cause to use this script recently to test two GSheet GIS tables (that use SheetSee.js to display results from a form submission). It works fine. You are warned about 'trust' for the script but once you agree, it all works. You need to give that approval for each sheet you run it with.
